# Generated by Django 5.1 on 2025-09-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0024_website_choosen_services_and_more'),
        ('Post', '0045_price_barter_price_en_price_barter_price_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('brand_description', models.TextField(max_length=500, null=True)),
                ('brand_link', models.URLField(null=True)),
                ('brand_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.media')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateLinkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(choices=[('None', 'None'), ('Home page', 'Home'), ('About page', 'Abot')], default='None', max_length=50)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Affiliate.affiliatelink')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Post.post')),
                ('tags', models.ManyToManyField(to='Post.tag')),
            ],
        ),
    ]
