# Generated by Django 5.1 on 2025-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0002_remove_affiliatelinkconnection_special_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='lang_type',
            field=models.CharField(choices=[('ru', 'Lang Type Ru'), ('en', 'Lang Type En'), ('XX', 'Lang Type Uni')], default='XX', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='langs',
            field=models.ManyToManyField(blank=True, to='Affiliate.affiliatelink'),
        ),
    ]
