# Generated by Django 4.2.6 on 2023-12-20 15:11

import Main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=Main.models.user_directory_path_forImageAndDownloadabel)),
                ('text', models.CharField(blank=True, max_length=250)),
                ('text_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('text_en', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Main.models.user_directory_path_forImageAndDownloadabel)),
                ('text', models.CharField(blank=True, max_length=250)),
                ('text_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('text_en', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
