# Generated by Django 5.1 on 2024-08-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, choices=[('Ar', 'Art'), ('Re', 'Resource')], default='Re', max_length=2),
        ),
    ]
