# Generated by Django 4.2.6 on 2023-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
