# Generated by Django 4.2.6 on 2023-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_downloadable_text_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='downloadable',
            name='text_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='text_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
