# Generated by Django 5.1 on 2024-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_image_timecreated_image_timeupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='category',
            field=models.CharField(blank=True, choices=[('Vi', 'Video'), ('Sc', 'Script'), ('Ac', 'Archive'), ('Tb', 'Telegram bot'), ('Pr', 'Parser')], default='Ac', max_length=2),
        ),
        migrations.AddField(
            model_name='downloadable',
            name='timeCreated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='downloadable',
            name='timeUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
