# Generated by Django 5.1 on 2024-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_downloadable_category_downloadable_timecreated_and_more'),
        ('Post', '0005_category_categry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='Post.tag'),
        ),
    ]
