# Generated by Django 5.1 on 2024-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_image_tags'),
        ('Post', '0016_article_h1_article_h1_en_article_h1_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('threshold_similar_articles', models.IntegerField(choices=[(1, 'No threshold (1)'), (2, 'Minimal threshold (2)'), (3, 'Tolerated threshold (3)'), (5, 'Maximal threshold (5)')], default=3, help_text='This field sets the threshold for tag matching between current viewed article and others articles.', verbose_name='Threshold for tag matching between articles')),
                ('threshold_related_termins', models.IntegerField(choices=[(1, 'No threshold (1)'), (2, 'Minimal threshold (2)'), (3, 'Tolerated threshold (3)'), (5, 'Maximal threshold (5)')], default=2, help_text='This field sets the threshold for tag matching between current viewed article and termins.', verbose_name='Threshold for tag matching between articles and termins')),
                ('threshold_related_questions', models.IntegerField(choices=[(1, 'No threshold (1)'), (2, 'Minimal threshold (2)'), (3, 'Tolerated threshold (3)'), (5, 'Maximal threshold (5)')], default=2, help_text='This field sets the threshold for tag matching between current viewed article and questions.', verbose_name='Threshold for tag matching between articles and questions')),
                ('max_displayed_similar_articles', models.IntegerField(choices=[(0, 'Do not display'), (2, 'Minimal display (2)'), (3, 'Tolerate display (3)'), (5, 'Maximal display (5)')], default=2, help_text='This field sets how many similar articles to display on the current viewed article.', verbose_name='How many sim. articles to display')),
                ('max_displayed_termins', models.IntegerField(choices=[(0, 'Do not display'), (2, 'Minimal display (2)'), (3, 'Tolerate display (3)'), (5, 'Maximal display (5)')], default=5, help_text='This field sets how many related termins to display on the current viewed article.', verbose_name='How many related termins to display')),
                ('max_displayed_questions', models.IntegerField(choices=[(0, 'Do not display'), (2, 'Minimal display (2)'), (3, 'Tolerate display (3)'), (5, 'Maximal display (5)')], default=3, help_text='This field sets how many related questions to display on the current viewed article.', verbose_name='How many related questions to display')),
                ('paginator_per_page_posts', models.IntegerField(default=4, help_text='This field sets how many posts should be loaded while scrolling or paginating', verbose_name='Posts per page')),
                ('paginator_per_page_gallery', models.IntegerField(default=4, help_text='This field sets how many images should be loaded while scrolling or paginating', verbose_name='Images per page')),
                ('paginator_per_page_gallery_columns', models.IntegerField(default=2, help_text='This field sets how many columns should be used for masonry', verbose_name='Columns to use for masonry')),
                ('min_displayed_my_resources', models.IntegerField(default=3, verbose_name='Minimum el in My resources part to be displayed if present')),
                ('min_displayed_other_articles', models.IntegerField(default=2, verbose_name='Minimum el in Other articles part to be displayed if present')),
                ('max_displayed_news_on_home', models.IntegerField(default=3, verbose_name='Limit to display Latest news')),
                ('max_displayed_postSeries_on_home', models.IntegerField(default=2, verbose_name='Limit to display post series')),
                ('max_displayed_images_on_home', models.IntegerField(default=3, verbose_name='Limit to display images')),
                ('categories_to_display_on_side_menu', models.ManyToManyField(to='Post.category', verbose_name='Categories to display on side menu')),
                ('my_resources_choosen_tags_on_home', models.ManyToManyField(related_name='my_resouces', to='Post.tag', verbose_name='Choosen tags for My resources part')),
                ('other_articles_choosen_tags_on_home', models.ManyToManyField(related_name='other_articles', to='Post.tag', verbose_name='Choosen tags for Other articles part')),
                ('popular_articles_on_footer', models.ManyToManyField(to='Post.article', verbose_name='Articles to display on footer')),
                ('popular_tools_on_footer', models.ManyToManyField(to='Post.tool', verbose_name='Tools(Archives) to display on footer')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Website',
                'db_table_comment': 'This is a general model of the site. It is created to manage all elements of the site, with the ability to switch between them (Different records of the model)',
            },
        ),
    ]
