# Generated by Django 5.1 on 2024-12-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_website_max_displayed_inner_tools_on_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='articles_post_preview',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
        migrations.AddField(
            model_name='website',
            name='qas_post_preview',
            field=models.ImageField(blank=True, upload_to='qa'),
        ),
        migrations.AddField(
            model_name='website',
            name='tds_post_preview',
            field=models.ImageField(blank=True, upload_to='td'),
        ),
        migrations.AddField(
            model_name='website',
            name='tools_post_preview',
            field=models.ImageField(blank=True, upload_to='tools'),
        ),
    ]
