# Generated by Django 5.1 on 2024-12-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_website_choosen_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='articles_post_preview',
            field=models.FileField(blank=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='website',
            name='default_image_preview',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='website',
            name='notes_post_preview',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='website',
            name='qas_post_preview',
            field=models.FileField(blank=True, upload_to='qa'),
        ),
        migrations.AlterField(
            model_name='website',
            name='tds_post_preview',
            field=models.FileField(blank=True, upload_to='td'),
        ),
        migrations.AlterField(
            model_name='website',
            name='tools_post_preview',
            field=models.FileField(blank=True, upload_to='tools'),
        ),
    ]
