# Generated by Django 5.1 on 2024-12-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_website_articles_post_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=512)),
            ],
        ),
    ]
