# Generated by Django 5.1 on 2025-04-13 07:11

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_remove_website_qas_post_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=Main.models.user_directory_path_forImageAndDownloadabel)),
            ],
        ),
    ]
