# Generated by Django 5.1 on 2025-04-13 17:54

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.AddField(
            model_name='media',
            name='lang_type',
            field=models.CharField(choices=[('ru', 'Lang Type Ru'), ('en', 'Lang Type En'), ('XX', 'Lang Type Uni')], default='XX', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='langs',
            field=models.ManyToManyField(blank=True, to='Main.media'),
        ),
        migrations.AddField(
            model_name='media',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='media',
            name='timeCreated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='timeUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.IntegerField(choices=[(1, 'files'), (2, 'pdfs'), (3, 'images'), (4, 'audios'), (5, 'videos')], default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=Main.models.Media.media_save_to),
        ),
        migrations.DeleteModel(
            name='Downloadable',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
