# Generated by Django 5.1 on 2025-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_remove_image_tags_remove_image_type_media_lang_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='articles_post_preview',
            field=models.FileField(blank=True, upload_to='common'),
        ),
        migrations.AlterField(
            model_name='website',
            name='notes_post_preview',
            field=models.FileField(blank=True, upload_to='common'),
        ),
        migrations.AlterField(
            model_name='website',
            name='tools_post_preview',
            field=models.FileField(blank=True, upload_to='common'),
        ),
    ]
