# Generated by Django 5.1 on 2025-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_website_articles_post_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='website',
            table_comment=None,
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
