# Generated by Django 4.1 on 2023-12-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/case.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/post_list.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/news.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/qa.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='service',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/service.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='td',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/td.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
    ]
