# Generated by Django 4.2.6 on 2023-12-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='lead',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead_ru',
            field=models.TextField(null=True),
        ),
    ]
