# Generated by Django 4.1 on 2024-07-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_case_template_alter_category_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
