# Generated by Django 5.0.3 on 2024-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_news_lead_alter_news_lead_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\case.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\post_list.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='news',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\news.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\qa.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='service',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\service.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='td',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\td.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
    ]
