# Generated by Django 4.1 on 2024-06-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_case_template_alter_category_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
