# Generated by Django 5.1 on 2024-09-03 15:02

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='archive',
            field=models.FileField(blank=True, help_text='Use only if it is Archive type', upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('In', 'Internal'), ('Ex', 'External'), ('Ac', 'Archive')], default='Ac', max_length=2),
        ),
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.URLField(blank=True, help_text='Use only if it is External type', max_length=300),
        ),
    ]
