# Generated by Django 5.1 on 2024-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_tool_archive_tool_type_tool_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='qas',
            field=models.ManyToManyField(blank=True, to='Post.qa'),
        ),
        migrations.AddField(
            model_name='article',
            name='tds',
            field=models.ManyToManyField(blank=True, to='Post.td'),
        ),
    ]
