# Generated by Django 5.1 on 2024-09-06 05:36

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_article_qas_article_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='default_template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\qa.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AddField(
            model_name='td',
            name='default_template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\td.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.TextField(max_length=360),
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer_en',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer_ru',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='description',
            field=models.TextField(help_text='To be used in meta tag - description', max_length=360),
        ),
        migrations.AlterField(
            model_name='qa',
            name='description_en',
            field=models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='description_ru',
            field=models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='template',
            field=models.FileField(blank=True, help_text='If provided, default template not in use', max_length=300, upload_to=Post.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='td',
            name='definition',
            field=models.TextField(max_length=360),
        ),
        migrations.AlterField(
            model_name='td',
            name='definition_en',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='td',
            name='definition_ru',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='td',
            name='description',
            field=models.TextField(help_text='To be used in meta tag - description', max_length=360),
        ),
        migrations.AlterField(
            model_name='td',
            name='description_en',
            field=models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='td',
            name='description_ru',
            field=models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='td',
            name='template',
            field=models.FileField(blank=True, help_text='If provided, default template not in use', max_length=300, upload_to=Post.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='td',
            name='termin',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='td',
            name='termin_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='td',
            name='termin_ru',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
