# Generated by Django 5.1 on 2024-09-06 05:39

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_qa_default_template_td_default_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='qa',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='td',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='td',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
    ]
