# Generated by Django 5.1 on 2024-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_qa_template_en_qa_template_ru_td_template_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='default_template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/qa.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='td',
            name='default_template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/td.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
    ]
