# Generated by Django 5.1 on 2024-09-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_qa_template_en_qa_template_ru_td_template_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
