# Generated by Django 5.1 on 2024-09-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_tag_name_en_tag_name_ru_tag_slug_tag_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='qas',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tds',
        ),
    ]
