# Generated by Django 5.1 on 2024-09-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_article_qas_article_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='h1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='h1_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='h1_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_ru',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='qas',
            field=models.ManyToManyField(blank=True, help_text='You only use this field to pin actualy needed qas. Other will come automatically', to='Post.qa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tds',
            field=models.ManyToManyField(blank=True, help_text='You only use this field to pin actualy needed tds. Other will come automatically', to='Post.td'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
