# Generated by Django 5.1 on 2024-10-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_article_h1_article_h1_en_article_h1_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('title_ru', models.CharField(default='', max_length=256, null=True)),
                ('title_en', models.CharField(default='', max_length=256, null=True)),
                ('description', models.TextField(default='', max_length=256)),
                ('description_ru', models.TextField(default='', max_length=256, null=True)),
                ('description_en', models.TextField(default='', max_length=256, null=True)),
                ('timeCreated', models.DateTimeField(auto_now=True)),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('isPublished', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.category')),
                ('tags', models.ManyToManyField(blank=True, to='Post.tag')),
            ],
        ),
    ]
