# Generated by Django 5.1 on 2024-12-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_alter_category_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='post',
            name='viewed',
        ),
    ]
