# Generated by Django 5.1 on 2025-01-07 05:04

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_remove_post_likes_remove_post_shares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='default_template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\tool.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
        migrations.AddField(
            model_name='tool',
            name='template',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, upload_to=Post.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='tool',
            name='archive',
            field=models.FileField(blank=True, help_text='Use only if it is Internal default type', upload_to=Post.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('In', 'Internal'), ('Ex', 'External'), ('Id', 'Internal default')], default='Id', max_length=2),
        ),
    ]
