# Generated by Django 5.1 on 2025-01-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0021_remove_tool_archive_remove_tool_type_remove_tool_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('name_en', models.CharField(max_length=256, null=True)),
                ('icon', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='Post.platform'),
        ),
    ]
