# Generated by Django 5.1 on 2025-01-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0021_tool_default_template_tool_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='url',
        ),
    ]
