# Generated by Django 5.1 on 2025-01-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0022_platform_tool_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('GameApplication', 'Gameapplication'), ('SocialNetworkingApplication', 'Socialnetworkingapplication'), ('TravelApplication', 'Travelapplication'), ('ShoppingApplication', 'Shoppingapplication'), ('SportsApplication', 'Sportsapplication'), ('LifestyleApplication', 'Lifestyleapplication'), ('BusinessApplication', 'Businessapplication'), ('DesignApplication', 'Designapplication'), ('DeveloperApplication', 'Developerapplication'), ('DriverApplication', 'Driverapplication'), ('EducationalApplication', 'Educationalapplication'), ('HealthApplication', 'Healthapplication'), ('FinanceApplication', 'Financeapplication'), ('SecurityApplication', 'Securityapplication'), ('BrowserApplication', 'Browserapplication'), ('CommunicationApplication', 'Communicationapplication'), ('DesktopEnhancementApplication', 'Desktopenhancementapplication'), ('EntertainmentApplication', 'Entertainmentapplication'), ('MultimediaApplication', 'Multimediaapplication'), ('HomeApplication', 'Homeapplication'), ('UtilitiesApplication', 'Utilitiesapplication'), ('ReferenceApplication', 'Referenceapplication'), ('VideoGame', 'Videogame'), ('MobileApplication', 'Mobileapplication'), ('WebApplication', 'Webapplication')], default='WebApplication', max_length=100),
        ),
    ]
