# Generated by Django 5.1 on 2025-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0025_remove_qa_default_template_remove_qa_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('question_ru', models.CharField(max_length=250, null=True)),
                ('question_en', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(help_text='To be used in meta tag - description', max_length=360)),
                ('description_ru', models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True)),
                ('description_en', models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True)),
                ('answer', models.TextField(max_length=360)),
                ('answer_ru', models.TextField(max_length=360, null=True)),
                ('answer_en', models.TextField(max_length=360, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.CharField(max_length=60)),
                ('termin_ru', models.CharField(max_length=60, null=True)),
                ('termin_en', models.CharField(max_length=60, null=True)),
                ('description', models.TextField(help_text='To be used in meta tag - description', max_length=360)),
                ('description_ru', models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True)),
                ('description_en', models.TextField(help_text='To be used in meta tag - description', max_length=360, null=True)),
                ('definition', models.TextField(max_length=360)),
                ('definition_ru', models.TextField(max_length=360, null=True)),
                ('definition_en', models.TextField(max_length=360, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='qas',
        ),
        migrations.RemoveField(
            model_name='td',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tds',
        ),
        migrations.AddField(
            model_name='post',
            name='similar',
            field=models.ManyToManyField(blank=True, to='Post.post'),
        ),
        migrations.AddField(
            model_name='article',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='You only use this field to pin actualy needed qas. Other will come automatically', to='Post.question'),
        ),
        migrations.AddField(
            model_name='article',
            name='termins',
            field=models.ManyToManyField(blank=True, help_text='You only use this field to pin actualy needed tds. Other will come automatically', to='Post.termin'),
        ),
        migrations.DeleteModel(
            name='QA',
        ),
        migrations.DeleteModel(
            name='TD',
        ),
    ]
