# Generated by Django 5.1 on 2025-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0026_question_termin_remove_article_qas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='similar',
        ),
        migrations.AddField(
            model_name='article',
            name='similar',
            field=models.ManyToManyField(blank=True, to='Post.article'),
        ),
    ]
