# Generated by Django 5.1 on 2025-05-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0029_alter_article_similar_alter_post_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
