# Generated by Django 5.1 on 2025-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0031_tool_h1_tool_h1_en_tool_h1_ru_tool_meta_keywords_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\PagiScroll\\templates\\PagiScroll\\base_post_list.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
    ]
