# Generated by Django 4.2.6 on 2024-02-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('shader_id', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('is_for_library', models.BooleanField(default=False)),
                ('fragment_src', models.TextField()),
                ('vertex_src', models.TextField()),
                ('default_geometry_data_indx', models.IntegerField(default=0)),
                ('render_mode', models.CharField(default='TRIANGLES', max_length=64)),
                ('bg', models.CharField(max_length=64)),
                ('buffers', models.TextField(default='')),
                ('sizes', models.TextField(default='')),
            ],
        ),
    ]
