# Generated by Django 5.1 on 2025-09-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0025_remove_website_choosen_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adblock_type', models.CharField(choices=[('Banner', 'Banner'), ('Full_screen', 'Full Screen'), ('Floor_full', 'Floor Full'), ('Top_full', 'Top Full'), ('Carousel', 'Carousel'), ('In_image', 'In Image')], default='Banner', max_length=50)),
                ('adnetwork_block_code', models.TextField(help_text='A part to display ad (in <body> tag)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('brand_description', models.TextField(max_length=500, null=True)),
                ('adnetwork_loader_code', models.TextField(help_text='A part to load nessessary 3-d party libraries (in <head> tag)', null=True)),
                ('adnetwork_type', models.ManyToManyField(to='AdManager.adblock')),
                ('brand_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.media')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAdNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_ad_network', to='AdManager.adnetwork')),
            ],
        ),
    ]
