# Generated by Django 5.1 on 2025-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adnetwork',
            name='brand_description',
        ),
        migrations.AddField(
            model_name='adblock',
            name='adblock_name',
            field=models.CharField(default='AdBlock name', max_length=50),
        ),
    ]
