# Generated by Django 5.1 on 2025-09-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0002_remove_adnetwork_brand_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adnetwork',
            old_name='adnetwork_type',
            new_name='adnetwork_blocks',
        ),
    ]
