# Generated by Django 5.1 on 2025-09-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0003_rename_adnetwork_type_adnetwork_adnetwork_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='adnetwork',
            name='adnetwork_step_by',
            field=models.IntegerField(default=3, help_text='To display an AdBlock every N iteration'),
        ),
    ]
