# Generated by Django 5.1 on 2025-09-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0004_adnetwork_adnetwork_step_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adnetwork',
            name='adnetwork_step_by',
        ),
    ]
