# Generated by Django 5.1 on 2025-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0005_remove_adnetwork_adnetwork_step_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adnetwork',
            name='adnetwork_step_by',
            field=models.IntegerField(default=3, help_text='To display an AdBlock every N iteration'),
        ),
    ]
