# Generated by Django 5.1 on 2025-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0006_adnetwork_adnetwork_step_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adblock',
            name='adnetwork_block_script_code',
            field=models.TextField(help_text='A script to use to call the ad)', null=True),
        ),
        migrations.AlterField(
            model_name='adblock',
            name='adnetwork_block_code',
            field=models.TextField(help_text='A part (HTML tag) to display ad (in <body> tag)', null=True),
        ),
    ]
