# Generated by Django 5.1 on 2025-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0007_adblock_adnetwork_block_script_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adblock',
            name='adnetwork_block_code',
        ),
        migrations.RemoveField(
            model_name='adblock',
            name='adnetwork_block_script_code',
        ),
        migrations.AddField(
            model_name='adblock',
            name='adblock_id',
            field=models.CharField(default='ID-0000000-0', help_text='An ID for block generated by Ad Network', max_length=50),
        ),
    ]
