# Generated by Django 5.1 on 2025-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0008_remove_adblock_adnetwork_block_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adnetwork',
            name='adnetwork_step_by',
        ),
        migrations.AlterField(
            model_name='adblock',
            name='adblock_id',
            field=models.CharField(default='ID-0000000-0', help_text='An ID for block generated by Ad Network. Please do not forget to change.', max_length=50),
        ),
    ]
