# Generated by Django 5.1 on 2025-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManager', '0010_adnetwork_adnetwork_step_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adblock',
            name='adblock_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('Full_screen', 'Full Screen'), ('Floor_full', 'Floor Full'), ('Top_full', 'Top Full'), ('feed', 'Carousel'), ('in_image', 'In Image')], default='banner', max_length=50),
        ),
    ]
