# Generated by Django 5.1 on 2024-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='time_updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
