# Generated by Django 5.1 on 2025-01-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0002_interaction_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (0, 'Zero')], default=0),
        ),
    ]
