# Generated by Django 5.1 on 2025-05-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0006_comment_is_root_comment_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_published',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
