# Generated by Django 5.1 on 2024-09-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_td_key_phrases_td_key_phrases_en_td_key_phrases_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(default='', max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_ru',
            field=models.SlugField(default='', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post\\article_list.html', path='C:\\Users\\dima\\Projects\\Web\\TimTheWebmaster\\MyBlog\\Post\\templates\\Post'),
        ),
    ]
