# Generated by Django 5.1 on 2024-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_remove_article_qas_remove_article_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='qas',
            field=models.ManyToManyField(blank=True, to='Post.qa'),
        ),
        migrations.AddField(
            model_name='article',
            name='tds',
            field=models.ManyToManyField(blank=True, to='Post.td'),
        ),
    ]
