# Generated by Django 5.1 on 2024-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='note',
            name='description_en',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description_ru',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='timeCreated',
            field=models.DateTimeField(),
        ),
    ]
