# Generated by Django 5.1 on 2024-10-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_alter_note_description_alter_note_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/article_list.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
    ]
