# Generated by Django 5.1 on 2025-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0025_tool_template_en_tool_template_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='default_template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post/tool.html', path='/home/t/timachuduk/timthewebmaster.com/MyBlog/Post/templates/Post'),
        ),
    ]
