# Generated by Django 5.1 on 2025-07-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0034_alter_category_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/Website/PagiScroll/templates/PagiScroll/base_post_list.html', path='/home/t/timachuduk/timthewebmaster.com/Website/Post/templates/Post'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='default_template',
            field=models.FilePathField(default='/home/t/timachuduk/timthewebmaster.com/Website/Post/templates/Post/tool.html', path='/home/t/timachuduk/timthewebmaster.com/Website/Post/templates/Post'),
        ),
    ]
