# Generated by Django 5.1 on 2025-07-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0035_alter_category_template_alter_tool_default_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.FilePathField(default='.\\PagiScroll\\templates\\PagiScroll\\base_post_list.html', path='.\\Post\\templates\\Post'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='default_template',
            field=models.FilePathField(default='.\\Post\\templates\\Post\\tool.html', path='.\\Post\\templates\\Post'),
        ),
    ]
