# Generated by Django 5.1 on 2025-07-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0037_alter_category_template_alter_tool_default_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='template',
        ),
    ]
