# Generated by Django 5.1 on 2025-07-25 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0038_remove_category_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FixPrice', 'Fixprice'), ('RangePrice', 'Rangeprice'), ('BarterPrice', 'Barterprice'), ('Free', 'Freeprice')], default='FixPrice', max_length=100)),
                ('currency', models.CharField(choices=[('$', 'Usd'), ('₽', 'Rub'), ('€', 'Eur'), ('₿', 'Btc')], default='$', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='', max_length=512)),
                ('timeCreated', models.DateTimeField()),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('isPublished', models.BooleanField(default=True)),
                ('duration', models.DurationField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.category')),
                ('price', models.ManyToManyField(to='Post.price')),
                ('tags', models.ManyToManyField(blank=True, to='Post.tag')),
            ],
        ),
    ]
