# Generated by Django 5.1 on 2025-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0039_price_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='barter_price',
            field=models.CharField(default='Что-нибудь взамен', max_length=100),
        ),
        migrations.AddField(
            model_name='price',
            name='end_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='price',
            name='start_price',
            field=models.FloatField(default=1.0),
        ),
    ]
