# Generated by Django 5.1 on 2025-07-25 08:50

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0040_price_barter_price_price_end_price_price_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preview',
            field=models.FileField(blank=True, upload_to=Post.models.service_path),
        ),
    ]
