# Generated by Django 5.1 on 2025-07-28 07:17

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0041_service_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.FileField(blank=True, max_length=300, upload_to=Post.models.user_directory_path),
        ),
    ]
