# Generated by Django 5.1 on 2025-07-28 09:13

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0042_alter_article_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='preview',
            field=models.FileField(blank=True, max_length=300, upload_to=Post.models.user_directory_path),
        ),
    ]
