# Generated by Django 5.1 on 2025-07-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0043_tool_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
