# Generated by Django 5.1 on 2025-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0044_service_description_en_service_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='barter_price_en',
            field=models.CharField(default='Что-нибудь взамен', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='barter_price_ru',
            field=models.CharField(default='Что-нибудь взамен', max_length=100, null=True),
        ),
    ]
