# Generated by Django 5.1 on 2025-09-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_remove_website_choosen_services_and_more'),
        ('Post', '0045_price_barter_price_en_price_barter_price_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
