# Generated by Django 5.2.7 on 2026-02-09 03:21

import Post.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_remove_website_choosen_services_and_more'),
        ('Post', '0046_remove_service_price_remove_service_category_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.tool')),
                ('target', models.CharField(help_text='What the main target of this scraper.', max_length=256)),
                ('how_many_threads', models.CharField(choices=[('Single Threaded', 'Singlethreaded'), ('Multi Threaded', 'Multithreaded')], default='Single Threaded', max_length=100)),
                ('what_type', models.CharField(choices=[('Static', 'Static'), ('Dynamic', 'Dynamic')], default='Static', max_length=100)),
                ('language_used', models.CharField(choices=[('Python', 'Python'), ('JS', 'Js')], default='Python', max_length=100)),
                ('with_proxies', models.CharField(choices=[('With Proxies', 'Withproxies'), ('No Proxies', 'Noproxies')], default='No Proxies', max_length=100)),
                ('with_swapping', models.CharField(choices=[('With Swapping', 'Withswapping'), ('No Swapping', 'Noswapping')], default='No Swapping', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('Post.tool',),
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.tool')),
                ('most_valuable_action_gif', models.ImageField(blank=True, help_text='Only gif type of image are allowed.', max_length=300, upload_to=Post.models.user_directory_path)),
                ('interface_type', models.CharField(choices=[('Only one command to run', 'Onerunner'), ('Command line interface', 'Commandlineinterface'), ('Terminal user interface', 'Terminaluserinterface')], default='Only one command to run', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('Post.tool',),
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.tool')),
                ('bot_name', models.CharField(max_length=256)),
                ('bot_type', models.CharField(choices=[('Chat bot', 'Chatbot'), ('Inline bot', 'Inlinebot'), ('Web bot', 'Webbot')], default='Chat bot', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('Post.tool',),
        ),
        migrations.CreateModel(
            name='WebTool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.tool')),
                ('landscape_preview', models.ImageField(blank=True, max_length=300, upload_to=Post.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('Post.tool',),
        ),
        migrations.RemoveField(
            model_name='tool',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='default_template',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='price',
        ),
        migrations.AddField(
            model_name='tool',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='DjangoApp',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.tool')),
                ('app_type', models.CharField(choices=[('Standalone App', 'Standaloneapp'), ('Middleware', 'Middleware'), ('API Hotspot', 'Apihotspot')], default='Standalone App', max_length=100)),
                ('use_cases', models.ManyToManyField(blank=True, help_text='Use cases of this app. Only images.', to='Main.media')),
            ],
            options={
                'abstract': False,
            },
            bases=('Post.tool',),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
