# Generated by Django 5.2.7 on 2026-02-09 03:53

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0047_scraper_script_telegrambot_webtool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='h1_en',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='h1_ru',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='meta_keywords_en',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='template_en',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='template_ru',
        ),
        migrations.AddField(
            model_name='webtool',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='h1_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='h1_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='webtool',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
    ]
