# Generated by Django 5.2.7 on 2026-02-09 03:56

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0048_remove_tool_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoapp',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='h1_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='h1_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='scraper',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='h1_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='h1_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='target_en',
            field=models.CharField(help_text='What the main target of this scraper.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='target_ru',
            field=models.CharField(help_text='What the main target of this scraper.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='scraper',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='script',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='h1_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='h1_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='script',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='h1_en',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='h1_ru',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='template_en',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='template_ru',
            field=models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path),
        ),
    ]
