# Generated by Django 5.2.7 on 2026-02-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0049_djangoapp_description_en_djangoapp_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='polymorphic_ctype',
        ),
    ]
