# Generated by Django 5.2.7 on 2026-02-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0051_tool_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='polymorphic_ctype',
        ),
    ]
