# Generated by Django 5.2.7 on 2026-02-09 16:04

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0053_tool_polymorphic_ctype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='most_valuable_action_gif',
            new_name='most_valuable_action',
        ),
        migrations.AlterField(
            model_name='scraper',
            name='what_type',
            field=models.CharField(choices=[('Static', 'Static'), ('Dynamic', 'Dynamic'), ('API', 'Api')], default='Static', max_length=100),
        ),
        migrations.AlterField(
            model_name='webtool',
            name='landscape_preview',
            field=models.FileField(blank=True, max_length=300, upload_to=Post.models.user_directory_path),
        ),
    ]
