# Generated by Django 5.2.7 on 2026-02-09 16:56

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0054_rename_most_valuable_action_gif_script_most_valuable_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='bot_qr',
            field=models.ImageField(blank=True, help_text='QR code of your TG bot', max_length=300, upload_to=Post.models.user_directory_path),
        ),
    ]
