# Generated by Django 5.2.7 on 2026-02-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_remove_website_choosen_services_and_more'),
        ('Post', '0055_telegrambot_bot_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Obsolete for articles, do not use', to='Main.media'),
        ),
    ]
