# Generated by Django 5.2.7 on 2026-02-22 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0056_alter_post_media_externalvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_type', models.CharField(choices=[('ru', 'Lang Type Ru'), ('en', 'Lang Type En'), ('XX', 'Lang Type Uni')], default='XX', max_length=2, null=True)),
                ('podcast_id', models.IntegerField(help_text='An ID for podcast', unique=True)),
                ('langs', models.ManyToManyField(blank=True, to='Post.externalpodcast')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_episode_id', models.IntegerField(help_text="Ad ID for podcast's episode", unique=True)),
                ('podcast_url', models.URLField(help_text='Full source path to podcast episode', unique=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.externalpodcast')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
