# Generated by Django 5.2.7 on 2026-02-22 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0057_alter_externalvideo_related_post_externalpodcast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=128, null=True)),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
