# Generated by Django 5.2.7 on 2026-03-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0058_externalvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dependencies',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='proficiencyLevel',
            field=models.CharField(choices=[('Beginer', 'Beginer'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('None', 'None')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='operatingSystem',
            field=models.CharField(choices=[('Any', 'Any'), ('Web', 'Web'), ('Windows', 'Windows'), ('Linux', 'Linux')], default='Any', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('GameApplication', 'Gameapplication'), ('SocialNetworkingApplication', 'Socialnetworkingapplication'), ('TravelApplication', 'Travelapplication'), ('ShoppingApplication', 'Shoppingapplication'), ('SportsApplication', 'Sportsapplication'), ('LifestyleApplication', 'Lifestyleapplication'), ('BusinessApplication', 'Businessapplication'), ('DesignApplication', 'Designapplication'), ('DeveloperApplication', 'Developerapplication'), ('DriverApplication', 'Driverapplication'), ('EducationalApplication', 'Educationalapplication'), ('HealthApplication', 'Healthapplication'), ('FinanceApplication', 'Financeapplication'), ('SecurityApplication', 'Securityapplication'), ('BrowserApplication', 'Browserapplication'), ('CommunicationApplication', 'Communicationapplication'), ('DesktopEnhancementApplication', 'Desktopenhancementapplication'), ('EntertainmentApplication', 'Entertainmentapplication'), ('MultimediaApplication', 'Multimediaapplication'), ('HomeApplication', 'Homeapplication'), ('UtilitiesApplication', 'Utilitiesapplication'), ('ReferenceApplication', 'Referenceapplication')], default='UtilitiesApplication', max_length=100),
        ),
    ]
