# Generated by Django 5.2.7 on 2026-03-09 15:13

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0059_article_dependencies_article_proficiencylevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_preview',
            field=models.ImageField(blank=True, help_text='If provided, then this preview is used in OG and Schema', max_length=256, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_preview_description',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_preview_description_en',
            field=models.CharField(blank=True, default='', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_preview_description_ru',
            field=models.CharField(blank=True, default='', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='meta_preview_description_en',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='djangoapp',
            name='meta_preview_description_ru',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='meta_preview_description_en',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='meta_preview_description_ru',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='meta_preview_description_en',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='meta_preview_description_ru',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_preview',
            field=models.ImageField(blank=True, help_text='If provided, then this preview is used in OG and Schema', max_length=300, upload_to=Post.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_preview_description',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256),
        ),
        migrations.AddField(
            model_name='webtool',
            name='meta_preview_description_en',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='webtool',
            name='meta_preview_description_ru',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
    ]
