# Generated by Django 5.2.7 on 2026-03-24 17:19

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0060_article_meta_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='template',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.notes_path),
        ),
        migrations.AddField(
            model_name='note',
            name='template_en',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.notes_path),
        ),
        migrations.AddField(
            model_name='note',
            name='template_ru',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.notes_path),
        ),
    ]
