# Generated by Django 5.2.7 on 2026-03-28 16:58

import Post.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0061_note_template_note_template_en_note_template_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_type', models.CharField(choices=[('ru', 'Lang Type Ru'), ('en', 'Lang Type En'), ('XX', 'Lang Type Uni')], default='XX', max_length=2, null=True)),
                ('podcast', models.FileField(max_length=300, upload_to=Post.models.podcast_path)),
                ('langs', models.ManyToManyField(blank=True, to='Post.internalpodcast')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
