# Generated by Django 5.2.7 on 2026-05-03 12:47

import Post.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0062_internalpodcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FixPrice', 'Fixprice'), ('RangePrice', 'Rangeprice'), ('BarterPrice', 'Barterprice'), ('Free', 'Freeprice')], default='FixPrice', max_length=100)),
                ('currency', models.CharField(choices=[('$', 'Usd'), ('₽', 'Rub'), ('€', 'Eur'), ('₿', 'Btc')], default='$', max_length=100)),
                ('start_price', models.FloatField(default=1.0)),
                ('end_price', models.FloatField(default=0.0)),
                ('barter_price', models.CharField(default='Что-нибудь взамен', max_length=100)),
                ('barter_price_ru', models.CharField(default='Что-нибудь взамен', max_length=100, null=True)),
                ('barter_price_en', models.CharField(default='Что-нибудь взамен', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('title_ru', models.CharField(default='', max_length=256, null=True)),
                ('title_en', models.CharField(default='', max_length=256, null=True)),
                ('description', models.TextField(default='', max_length=512)),
                ('description_ru', models.TextField(default='', max_length=512, null=True)),
                ('description_en', models.TextField(default='', max_length=512, null=True)),
                ('preview', models.FileField(blank=True, upload_to=Post.models.service_path)),
                ('timeCreated', models.DateTimeField()),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('isPublished', models.BooleanField(default=True)),
                ('duration', models.DurationField()),
                ('template', models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.notes_path)),
                ('template_ru', models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.notes_path)),
                ('template_en', models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.notes_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.category')),
                ('price', models.ManyToManyField(to='Post.price')),
                ('tags', models.ManyToManyField(blank=True, to='Post.tag')),
            ],
        ),
    ]
