# Generated by Django 5.2.7 on 2026-05-04 15:00

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0063_price_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='template',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.service_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='template_en',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.service_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='template_ru',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=Post.models.service_path),
        ),
    ]
