# Generated by Django 5.2.7 on 2026-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0064_alter_service_template_alter_service_template_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='meta_preview_description_en',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='meta_preview_description_ru',
            field=models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True),
        ),
    ]
