# Generated by Django 5.2.7 on 2026-06-09 17:42

import Post.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0065_scraper_meta_preview_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extention',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.tool')),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('name_en', models.CharField(max_length=256, null=True)),
                ('h1_ru', models.CharField(default='', max_length=256, null=True)),
                ('h1_en', models.CharField(default='', max_length=256, null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('meta_keywords_ru', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('meta_keywords_en', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('meta_preview_description_ru', models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True)),
                ('meta_preview_description_en', models.CharField(blank=True, default='', help_text='If provided, then this preview description is used in OG and Schema', max_length=256, null=True)),
                ('template_ru', models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path)),
                ('template_en', models.FileField(blank=True, help_text='If provided, default template not in use. Use only if it is Internal default type', max_length=300, null=True, upload_to=Post.models.user_directory_path)),
                ('engine_used', models.CharField(choices=[('Blink', 'Blink'), ('Gecko', 'Gecko'), ('Webkit', 'Webkit')], default='Blink', max_length=100)),
                ('minimal_version_required', models.IntegerField()),
                ('shop_url', models.URLField(help_text='Full source path to extension on a shop website', unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Post.tool',),
        ),
    ]
