# Generated by Django 6.1 on 2026-09-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0066_extention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='icon',
        ),
    ]
