# Generated by Django 6.1 on 2026-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0068_post_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='source',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
