# Generated by Django 5.1 on 2024-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Should be checked only for one record of Website databse'),
        ),
    ]
