# Generated by Django 5.1 on 2024-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_website_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='max_displayed_inner_tools_on_home',
            field=models.IntegerField(default=3, verbose_name='Limit to display inner tools'),
        ),
        migrations.AddField(
            model_name='website',
            name='max_displayed_notes_on_home',
            field=models.IntegerField(default=5, verbose_name='Limit to display notes'),
        ),
        migrations.AddField(
            model_name='website',
            name='max_displayed_qa_on_home',
            field=models.IntegerField(default=2, verbose_name='Limit to display termins'),
        ),
        migrations.AddField(
            model_name='website',
            name='max_displayed_td_on_home',
            field=models.IntegerField(default=2, verbose_name='Limit to display questions'),
        ),
    ]
