# Generated by Django 5.1 on 2024-12-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_website_articles_post_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='default_icon_preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='website',
            name='default_image_preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
