# Generated by Django 5.1 on 2024-12-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
