# Generated by Django 5.1 on 2025-03-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_contact_description_en_contact_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='qas_post_preview',
        ),
        migrations.RemoveField(
            model_name='website',
            name='tds_post_preview',
        ),
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.FileField(upload_to='common/contacts'),
        ),
        migrations.AlterField(
            model_name='website',
            name='default_image_preview',
            field=models.FileField(blank=True, upload_to='common'),
        ),
        migrations.AlterField(
            model_name='website',
            name='notes_post_preview',
            field=models.FileField(blank=True, upload_to='notes'),
        ),
    ]
