# Generated by Django 5.1 on 2025-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_alter_website_table_comment_alter_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='contacts_for_orders',
            field=models.ManyToManyField(blank=True, to='Main.contact', verbose_name='Contacts to use for ordering'),
        ),
    ]
