# Generated by Django 5.1 on 2025-07-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_website_contacts_for_orders'),
        ('Post', '0044_service_description_en_service_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='choosen_services',
            field=models.ManyToManyField(blank=True, related_name='choosen_services', to='Post.service', verbose_name='Services to display at home page'),
        ),
        migrations.AddField(
            model_name='website',
            name='max_displayed_services_on_home',
            field=models.IntegerField(default=6, verbose_name='Limit to display Services'),
        ),
    ]
