# Generated by Django 5.1 on 2025-09-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_website_choosen_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='choosen_services',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_services_on_home',
        ),
    ]
