# Generated by Django 5.2.7 on 2026-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_remove_website_choosen_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_slug', models.CharField(help_text='A regex expression, which represents urls', max_length=512, unique=True)),
                ('message', models.TextField(help_text='You can also use an HTML tags.', max_length=256)),
            ],
        ),
    ]
