# Generated by Django 6.1 on 2026-09-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_commonnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_questions',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_similar_articles',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_termins',
        ),
        migrations.RemoveField(
            model_name='website',
            name='paginator_per_page_gallery',
        ),
        migrations.RemoveField(
            model_name='website',
            name='paginator_per_page_gallery_columns',
        ),
        migrations.RemoveField(
            model_name='website',
            name='threshold_related_questions',
        ),
        migrations.RemoveField(
            model_name='website',
            name='threshold_related_termins',
        ),
        migrations.RemoveField(
            model_name='website',
            name='threshold_similar_articles',
        ),
    ]
