# Generated by Django 6.1 on 2026-09-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_remove_website_max_displayed_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='choosen_tools',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_images_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_inner_tools_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_news_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_postSeries_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_qa_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_displayed_td_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='min_displayed_my_resources',
        ),
        migrations.RemoveField(
            model_name='website',
            name='min_displayed_other_articles',
        ),
        migrations.RemoveField(
            model_name='website',
            name='my_resources_choosen_tags_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='other_articles_choosen_tags_on_home',
        ),
        migrations.RemoveField(
            model_name='website',
            name='popular_articles_on_footer',
        ),
        migrations.RemoveField(
            model_name='website',
            name='popular_tools_on_footer',
        ),
    ]
