# Generated by Django 5.1 on 2025-01-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostEditor', '0002_alter_posttemplate_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplate',
            name='option',
            field=models.IntegerField(choices=[(0, 'Чистый HTML'), (1, 'Для статей'), (2, 'Для определений'), (3, 'Для вопросов'), (4, 'Для инструментов')], default=0),
        ),
    ]
