# Generated by Django 5.1 on 2025-07-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostEditor', '0004_alter_posttemplate_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplate',
            name='template',
            field=models.FilePathField(path='/home/t/timachuduk/timthewebmaster.com/Website/media/tools/post-editor'),
        ),
    ]
