# Generated by Django 5.1 on 2025-07-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostEditor', '0006_alter_posttemplate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplate',
            name='template',
            field=models.FilePathField(path='./media/tools/post-editor'),
        ),
    ]
