# Generated by Django 4.1 on 2023-11-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('anonymous_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('replies', models.ManyToManyField(blank=True, to='Comment.comment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
