# Generated by Django 5.1 on 2025-03-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0004_alter_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
