# Generated by Django 5.0.3 on 2024-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSAggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
