# Generated by Django 5.1 on 2025-05-23 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSAggregator', '0002_alter_feed_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='group',
        ),
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='FeedId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('similar_user_id', models.ManyToManyField(blank=True, to='RSSAggregator.feedid')),
            ],
        ),
        migrations.CreateModel(
            name='FeedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_common', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('feeds', models.ManyToManyField(blank=True, to='RSSAggregator.feed')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSSAggregator.feedid')),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSSAggregator.feedid'),
        ),
    ]
