# Generated by Django 5.1 on 2025-05-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSSAggregator', '0003_remove_feed_group_feed_name_feedid_feedgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='source',
            new_name='feed',
        ),
    ]
