# Generated by Django 5.1 on 2025-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSAggregator', '0006_alter_feed_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedid',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedid',
            name='sort',
            field=models.IntegerField(choices=[(0, 'Latest First'), (1, 'Earliest First')], default=0),
        ),
        migrations.AddField(
            model_name='feedid',
            name='with_previews',
            field=models.BooleanField(default=True),
        ),
    ]
