# Generated by Django 5.1 on 2025-02-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagiScrollEditor', '0002_alter_postfilter_description_alter_postfilter_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFilter',
            new_name='PagiScrollPage',
        ),
    ]
