# Generated by Django 5.1 on 2025-03-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagiScrollEditor', '0003_rename_postfilter_pagiscrollpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagiscrollpage',
            name='preview',
        ),
    ]
