# Generated by Django 5.2.7 on 2026-03-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Engagement', '0007_alter_comment_time_published'),
        ('Post', '0060_article_meta_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPayCrowdfundApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=256, unique=True)),
                ('language_code', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], db_index=True, max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.tool')),
            ],
        ),
        migrations.CreateModel(
            name='BTCPayCrowdfundDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(help_text="An invoice's ID to bind to this email")),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTCPayCrowdfunding.btcpaycrowdfundapp')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engagement.email')),
            ],
        ),
    ]
