# Generated by Django 5.2.7 on 2026-03-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTCPayCrowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcpaycrowdfunddonation',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='btcpaycrowdfunddonation',
            name='receipt_id',
            field=models.CharField(default=None, help_text='This must be generated after InvoiceSettled', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='btcpaycrowdfunddonation',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
