# Generated by Django 5.2.7 on 2026-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTCPayCrowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcpaycrowdfunddonation',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Expired'), (3, 'Invalid'), (4, 'Settled')], default=0),
        ),
    ]
