# Generated by Django 5.2.7 on 2026-03-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTCPayCrowdfunding', '0002_btcpaycrowdfunddonation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcpaycrowdfunddonation',
            name='invoice_id',
            field=models.CharField(help_text="An invoice's ID to bind to this email", max_length=256),
        ),
    ]
