# Generated by Django 5.2.7 on 2026-03-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTCPayCrowdfunding', '0002_btcpaycrowdfunddonation_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcpaycrowdfunddonation',
            name='receipt_id',
            field=models.CharField(blank=True, default=None, help_text='This must be generated after InvoiceSettled', max_length=64, null=True, unique=True),
        ),
    ]
