# Generated by Django 5.1 on 2025-05-03 16:49

import Apps.LinkThief.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkThiefRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Apps.LinkThief.models.file_path)),
            ],
        ),
    ]
