# Generated by Django 5.2.7 on 2026-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagiScrollPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_slug', models.CharField(help_text='A regex expression, which represents urls', max_length=512, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Will be used only if provided with description', max_length=256)),
                ('h1', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Will be used only if provided with title', max_length=256)),
                ('lead', models.TextField(blank=True, max_length=768)),
            ],
        ),
    ]
