# Generated by Django 5.2.7 on 2026-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagiScrollEditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagiscrollpage',
            name='conclusion',
            field=models.TextField(blank=True, max_length=768),
        ),
    ]
