# Generated by Django 5.1 on 2025-09-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYSIWYGEditor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttemplate',
            name='option',
        ),
        migrations.AlterField(
            model_name='posttemplate',
            name='template',
            field=models.FilePathField(path='./media/tools/wysiwyg-editor'),
        ),
    ]
