# Generated by Django 5.1 on 2024-10-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostEditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplate',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
