# Generated by Django 5.1 on 2025-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostEditor', '0003_alter_posttemplate_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplate',
            name='option',
            field=models.IntegerField(choices=[(0, 'Чистый HTML'), (1, 'Для статей'), (2, 'Для инструментов')], default=0),
        ),
    ]
