# Generated by Django 5.1 on 2024-12-11 18:55

import PostFilterEditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_slug', models.CharField(help_text='A regex expression, which represents urls', max_length=512, unique=True)),
                ('preview', models.ImageField(blank=True, max_length=300, upload_to=PostFilterEditor.models.filter_pages_path)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('h1', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('lead', models.TextField(blank=True, max_length=768)),
            ],
        ),
    ]
