# Generated by Django 5.1 on 2024-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostFilterEditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilter',
            name='description',
            field=models.TextField(blank=True, help_text='Will be used only if provided with title', max_length=256),
        ),
        migrations.AlterField(
            model_name='postfilter',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Will be used only if provided with description', max_length=256),
        ),
    ]
