# Generated by Django 5.1 on 2025-05-27 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSAggregator', '0004_rename_source_feed_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RSSAggregator.feedid'),
        ),
    ]
