# Generated by Django 5.1 on 2025-09-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WYSIWYGEditor', '0002_remove_posttemplate_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttemplate',
            name='user',
        ),
    ]
