# Generated by Django 5.2.7 on 2026-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYSIWYGEditor', '0003_remove_posttemplate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'article_exmpl.html'), (2, 'tool_exmpl.html'), (3, 'note_exmpl.html')], default=1),
        ),
    ]
