# Generated by Django 5.1 on 2025-06-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RSSAggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('feed', models.URLField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('sort', models.IntegerField(choices=[(0, 'Latest First'), (1, 'Earliest First')], default=0)),
                ('posts_per_page', models.PositiveIntegerField(default=5)),
                ('with_previews', models.BooleanField(default=True)),
                ('similar_user_id', models.ManyToManyField(blank=True, to='RSSAggregator.feedid')),
            ],
        ),
        migrations.CreateModel(
            name='FeedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_common', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('feeds', models.ManyToManyField(blank=True, to='RSSAggregator.feed')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSSAggregator.feedid')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RSSAggregator.feedid'),
        ),
    ]
